# Generated by Django 3.1.6 on 2021-03-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_cart',
            new_name='original_basket',
        ),
    ]
